import os
import json


def create_dummy_file(base_dir, relative_path, key_id):
    """Helper to write the actual file"""
    # Clean up the path (handling slashes for Windows)
    full_path = os.path.join(base_dir, os.path.normpath(relative_path))

    # Ensure folder exists
    os.makedirs(os.path.dirname(full_path), exist_ok=True)

    # Write file if missing
    if not os.path.exists(full_path):
        dummy_content = {
            "id": key_id,
            "text": {
                "en": f"[PLACEHOLDER] Content for {key_id}",
                "note": "Generated by initialize_assets.py"
            }
        }
        with open(full_path, "w", encoding="utf-8") as out:
            json.dump(dummy_content, out, indent=2)
        return True
    return False


def process_mapping(base_path, data_map):
    """Recursively parses the map to find file strings"""
    count = 0
    for key, value in data_map.items():
        if isinstance(value, dict):
            # It's a nested category (e.g. "tone_1"), dive deeper
            count += process_mapping(base_path, value)
        elif isinstance(value, str):
            # It's a file path string
            if create_dummy_file(os.getcwd(), os.path.join(base_path, value), key):
                count += 1
                print(f"Created: {value}")
    return count


def init_assets():
    print("--- 🚀 Initializing Assets Database ---")

    # 1. Load the Map
    map_path = os.path.join("json_db", "03_assets_map.json")
    if not os.path.exists(map_path):
        print(f"❌ Error: {map_path} not found.")
        return

    with open(map_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # 2. Iterate domains
    total_created = 0
    domains = data.get("asset_domains", {})

    for domain_name, content in domains.items():
        base = content.get("base_path", "")
        mapping = content.get("map", {})

        # Start recursive processing
        total_created += process_mapping(base, mapping)

    print(f"\n✅ Operation Complete. {total_created} new files generated.")


if __name__ == "__main__":
    init_assets()