import os
import ast

def generate_python_index(root_dir):
    index_lines = []
    index_lines.append("# Python Codebase Master Index")
    index_lines.append("> Autogenerated index of Python modules, classes, and methods.\n")
    
    # Target files/dirs
    targets = [
        "ruthenian_engine.py",
        "typikon_digest_generator.py",
        "scripts"
    ]
    
    file_details = []
    
    for target in targets:
        path = os.path.join(root_dir, target)
        if os.path.isfile(path):
             file_details.append(path)
        elif os.path.isdir(path):
             for root, dirs, files in os.walk(path):
                 for file in files:
                     if file.endswith(".py"):
                         file_details.append(os.path.join(root, file))
    
    for file_path in file_details:
        rel_path = os.path.relpath(file_path, root_dir)
        index_lines.append(f"## Module: `{rel_path}`")
        
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                content = f.read()
                tree = ast.parse(content)
                
            # Module Docstring
            module_doc = ast.get_docstring(tree)
            if module_doc:
                index_lines.append(f"> {module_doc.strip().splitlines()[0]}...")
            index_lines.append("")
            
            # Function/Class Scanning
            for node in tree.body:
                if isinstance(node, ast.ClassDef):
                    index_lines.append(f"### Class: `{node.name}`")
                    class_doc = ast.get_docstring(node)
                    if class_doc: index_lines.append(f"_{class_doc.strip().splitlines()[0]}_")
                    
                    index_lines.append("| Method | Arguments | Line | Summary |")
                    index_lines.append("| --- | --- | --- | --- |")
                    
                    for subnode in node.body:
                        if isinstance(subnode, ast.FunctionDef):
                            args = [a.arg for a in subnode.args.args]
                            arg_str = ", ".join(args)
                            func_doc = ast.get_docstring(subnode) or "-"
                            summary = func_doc.strip().splitlines()[0]
                            index_lines.append(f"| `{subnode.name}` | `({arg_str})` | {subnode.lineno} | {summary} |")
                    index_lines.append("")

                elif isinstance(node, ast.FunctionDef):
                    # Top-level functions
                    args = [a.arg for a in node.args.args]
                    arg_str = ", ".join(args)
                    func_doc = ast.get_docstring(node) or "-"
                    summary = func_doc.strip().splitlines()[0]
                    index_lines.append(f"### Function: `{node.name}`")
                    index_lines.append(f"- **Line**: {node.lineno}")
                    index_lines.append(f"- **Args**: `({arg_str})`")
                    index_lines.append(f"- **Summary**: {summary}")
                    index_lines.append("")
            
            # Extract Critical Comments (TODOs, NOTEs, RULEs)
            index_lines.append("#### Commentary & Rules")
            lines = content.splitlines()
            found_comments = False
            for i, line in enumerate(lines):
                 stripped = line.strip()
                 if stripped.startswith("# NOTE:") or stripped.startswith("# RULE:") or stripped.startswith("# TODO:") or stripped.startswith("# FIX:"):
                      index_lines.append(f"- **L{i+1}**: {stripped}")
                      found_comments = True
            
            if not found_comments:
                index_lines.append("_No critical comments found._")
            index_lines.append("\n---")

        except Exception as e:
            index_lines.append(f"_Error parsing file: {e}_")
            
    return "\n".join(index_lines)

if __name__ == "__main__":
    root_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
    output_path = os.path.join(root_dir, 'docs', 'index_python_master.md')
    
    print(f"Scanning {root_dir}...")
    content = generate_python_index(root_dir)
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Generated index at {output_path}")
