import os
import json

def generate_json_index(root_dir):
    index_lines = []
    index_lines.append("# JSON Database Master Index")
    index_lines.append("> Autogenerated index of all JSON assets in `json_db/`.\n")
    
    index_lines.append("## File Overview")
    index_lines.append("| Filename | Directory | Size (Bytes) | Description |")
    index_lines.append("| --- | --- | --- | --- |")
    
    file_details = []
    
    for root, dirs, files in os.walk(root_dir):
        files.sort() # Ensure deterministic order
        for file in files:
            if file.endswith(".json"):
                path = os.path.join(root, file)
                rel_path = os.path.relpath(path, root_dir)
                size = os.path.getsize(path)
                
                desc = "-"
                data = {}
                try:
                    with open(path, 'r', encoding='utf-8') as f:
                        data = json.load(f)
                        if "file_metadata" in data:
                            desc = data["file_metadata"].get("description", "-")
                        elif "metadata" in data:
                            desc = data["metadata"].get("description", "-")
                        elif "title" in data:
                            desc = f"Title: {data['title']}"
                except Exception as e:
                    desc = f"Error reading file: {e}"
                    
                parent_dir = os.path.dirname(rel_path)
                if not parent_dir: parent_dir = "(root)"
                
                desc = str(desc).replace("\n", " ") # Sanitize for table
                index_lines.append(f"| [{file}](file:///{path.replace(os.sep, '/')}) | {parent_dir} | {size} | {desc} |")
                
                file_details.append({"path": path, "rel_path": rel_path, "data": data})

    index_lines.append("\n## Detail Index")
    
    for detail in file_details:
        rel_path = detail["rel_path"]
        data = detail.get("data", {})
        
        index_lines.append(f"\n### `{rel_path}`")
        if isinstance(data, dict):
            keys = list(data.keys())
            index_lines.append(f"- **Top-Level Keys**: {', '.join(keys)}")
            
            # Specific Section Parsing
            if "variables" in data:
                 index_lines.append(f"- **Variables**: {len(data['variables'])} items")
            if "cases" in data:
                 index_lines.append(f"- **Cases**: {len(data['cases'])} definitions (IDs: {', '.join(list(data['cases'].keys())[:5])}...)")
            if "structure" in data:
                 index_lines.append("- **Structure Definition**: Present")
            if "month_settings" in data:
                 days = data["month_settings"].get("days", {})
                 index_lines.append(f"- **Month Settings**: {len(days)} days defined")
            if "logic_map" in data:
                 index_lines.append(f"- **Logic Map**: {len(data['logic_map'])} entries")
        
        index_lines.append("")

    return "\n".join(index_lines)

if __name__ == "__main__":
    # Adjust paths based on where script is run
    root_json_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'json_db'))
    output_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'docs', 'index_json_master.md'))
    
    print(f"Scanning {root_json_dir}...")
    content = generate_json_index(root_json_dir)
    
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
        
    print(f"Generated index at {output_path}")
