import os
import sys
import json
import requests
from pathlib import Path
from dotenv import load_dotenv

def get_deepseek_key():
    key = os.getenv("DEEPSEEK_API_KEY")
    if key and key != "your_deepseek_api_key_here":
        return key

    global_env = r"C:\Users\augus\OneDrive\Documents\Google Antigravity\Projects\.env"
    if os.path.exists(global_env):
        try:
            with open(global_env, "r", encoding="utf-8") as f:
                for line in f:
                    if "=" in line:
                        k, v = line.split("=", 1)
                        k_clean = k.strip().replace("[", "").replace("]", "")
                        if k_clean in ("deepseek-v4-pro", "DEEPSEEK_API_KEY"):
                            val = v.strip()
                            if val:
                                return val
        except Exception as e:
            print(f"Warning: Error reading global .env: {e}", file=sys.stderr)

    if os.path.exists(".env"):
        try:
            with open(".env", "r", encoding="utf-8") as f:
                for line in f:
                    if "=" in line:
                        k, v = line.split("=", 1)
                        k_clean = k.strip().replace("[", "").replace("]", "")
                        if k_clean in ("deepseek-v4-pro", "DEEPSEEK_API_KEY"):
                            val = v.strip()
                            if val and val != "your_deepseek_api_key_here":
                                return val
        except Exception as e:
            print(f"Warning: Error reading local .env: {e}", file=sys.stderr)

    return None

def main():
    if len(sys.argv) < 2:
        print("Usage: python perfect_plan_via_deepseek.py <path_to_plan_or_task_md>", file=sys.stderr)
        sys.exit(1)

    file_path = Path(sys.argv[1])
    if not file_path.exists():
        print(f"Error: File {file_path} does not exist.", file=sys.stderr)
        sys.exit(1)

    content = file_path.read_text(encoding="utf-8")
    
    # Check if already perfected
    if "[GENERATOR: DeepSeek-V4-Pro]" in content:
        print("Plan is already perfected by DeepSeek. Skipping.")
        sys.exit(0)

    # Detect current generator (default to Gemini 3.5 Flash if not tagged)
    if "[GENERATOR:" not in content:
        content = f"<!-- [GENERATOR: Gemini 3.5 Flash] -->\n{content}"
        file_path.write_text(content, encoding="utf-8")
        print("Tagged plan as generated by Gemini 3.5 Flash.")

    api_key = get_deepseek_key()
    if not api_key:
        print("Error: DEEPSEEK_API_KEY not found.", file=sys.stderr)
        sys.exit(1)

    print("Loading brain files for grounding...")
    agents_md = Path(".agents/AGENTS.md").read_text(encoding="utf-8")
    anti_patterns = Path(".agents/references/anti_patterns.md").read_text(encoding="utf-8")
    project_facts = Path(".agents/references/project_facts.md").read_text(encoding="utf-8")

    prompt = f"""
You are the senior liturgical architect and perfection gatekeeper. Your task is to take an implementation plan or task checklist generated by another model (Gemini 3.5 Flash) and "perfect" it.

A perfected plan MUST:
1. Be 100% compliant with the Honesty Protocol, the Evidence Gate, and all rules in AGENTS.md.
2. Check that the plan's components and files do not introduce any of the 14 blacklisted anti-patterns.
3. Verify that the UGCC Royal Doors terminology map is strictly enforced (e.g. Exapostilarion, Irmos, Prokeimenon, Sessional Hymn).
4. Add clear, detailed step-by-step verification commands using pytest or git --no-pager diff.
5. Contain the tag: <!-- [GENERATOR: DeepSeek-V4-Pro] --> at the very top.

Here is the current draft plan to perfect:
--------------------------------------------
{content}
--------------------------------------------

Grounding Brain Files:
=== AGENTS.MD ===
{agents_md}

=== ANTI-PATTERNS ===
{anti_patterns}

=== PROJECT FACTS ===
{project_facts}

Please rewrite and perfect the plan. Return ONLY the perfected markdown content. Do not include markdown code block formatting (like ```markdown) around your output, return only the raw perfected document text starting with the tag.
"""

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json"
    }

    payload = {
        "model": "deepseek-v4-pro",
        "messages": [
            {"role": "system", "content": "You are the senior architect. Return the perfected markdown directly without markdown code blocks."},
            {"role": "user", "content": prompt}
        ],
        "thinking": {"type": "enabled"},
        "max_tokens": 8000
    }

    print(f"Sending plan {file_path.name} to DeepSeek for perfection...")
    try:
        response = requests.post("https://api.deepseek.com/chat/completions", headers=headers, json=payload)
        response.raise_for_status()
        data = response.json()
        perfected_content = data['choices'][0]['message']['content'].strip()

        # Strip code block decorators if present
        if perfected_content.startswith("```markdown"):
            perfected_content = perfected_content[11:]
        elif perfected_content.startswith("```"):
            perfected_content = perfected_content[3:]
        if perfected_content.endswith("```"):
            perfected_content = perfected_content[:-3]
        perfected_content = perfected_content.strip()

        # Ensure the tag is at the top
        if "GENERATOR: DeepSeek-V4-Pro" not in perfected_content:
            perfected_content = f"<!-- [GENERATOR: DeepSeek-V4-Pro] -->\n{perfected_content}"

        file_path.write_text(perfected_content, encoding="utf-8")
        print(f"Success! Perfected plan saved to {file_path}")

    except Exception as e:
        print(f"Error calling DeepSeek API: {e}", file=sys.stderr)
        if 'response' in locals() and response is not None:
            print(response.text, file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
